#include "shader_loader.h"
#include <cstring>

// Include embedded shader data (generated by xxd)
#include "capillary_map.h"
#include "ink_physics.h"
#include "ink_composite.h"
#include "paper_generation.h"

static GLuint loadShaderFromSPIRV(const void* data, size_t size) {
    GLuint shader = glCreateShader(GL_COMPUTE_SHADER);
    if (!shader) return 0;

    glShaderBinary(1, &shader, GL_SHADER_BINARY_FORMAT_SPIR_V, data, size);
    if (glGetError() != GL_NO_ERROR) {
        glDeleteShader(shader);
        return 0;
    }

    glSpecializeShader(shader, "main", 0, nullptr, nullptr);
    if (glGetError() != GL_NO_ERROR) {
        glDeleteShader(shader);
        return 0;
    }

    return shader;
}

GLuint createComputeProgram(const void* data, size_t size) {
    GLuint shader = loadShaderFromSPIRV(data, size);
    if (!shader) return 0;

    GLuint program = glCreateProgram();
    glAttachShader(program, shader);
    glLinkProgram(program);

    GLint status;
    glGetProgramiv(program, GL_LINK_STATUS, &status);
    if (!status) {
        char log[512];
        glGetProgramInfoLog(program, sizeof(log), nullptr, log);
        glDeleteProgram(program);
        return 0;
    }
    glDeleteShader(shader);
    return program;
}

// ---- Cached programs ----

GLuint getCapillaryProgram() {
    static GLuint program = 0;
    if (!program) {
        program = createComputeProgram(capillary_map_spv, capillary_map_spv_len);
    }
    return program;
}

GLuint getPhysicsProgram() {
    static GLuint program = 0;
    if (!program) {
        program = createComputeProgram(ink_physics_spv, ink_physics_spv_len);
    }
    return program;
}

GLuint getCompositeProgram() {
    static GLuint program = 0;
    if (!program) {
        program = createComputeProgram(ink_composite_spv, ink_composite_spv_len);
    }
    return program;
}

GLuint getPaperProgram() {
    static GLuint program = 0;
    if (!program) {
        program = createComputeProgram(paper_generation_spv, paper_generation_spv_len);
    }
    return program;
}